// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRhwZ9-1fFIA6uuNI-Y56fScr1PLwTIQ',
    appId: '1:312052389013:web:58dd695bb8212c7273379c',
    messagingSenderId: '312052389013',
    projectId: 'todolist-31d6e',
    authDomain: 'todolist-31d6e.firebaseapp.com',
    storageBucket: 'todolist-31d6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTcYiloQmL9JwY8PjU6OBNr-fo-BvPUo',
    appId: '1:312052389013:android:6b302ac8d87fe07073379c',
    messagingSenderId: '312052389013',
    projectId: 'todolist-31d6e',
    storageBucket: 'todolist-31d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxju27e30X7bD-NS17KGWvxFKWcg-Ay5g',
    appId: '1:312052389013:ios:086a9ac90268bab273379c',
    messagingSenderId: '312052389013',
    projectId: 'todolist-31d6e',
    storageBucket: 'todolist-31d6e.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxju27e30X7bD-NS17KGWvxFKWcg-Ay5g',
    appId: '1:312052389013:ios:8eb23b1fdf1bd30c73379c',
    messagingSenderId: '312052389013',
    projectId: 'todolist-31d6e',
    storageBucket: 'todolist-31d6e.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
